// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOgRZc8WEidshArMsWX0o9b9UjcvktgGg',
    appId: '1:283652485039:web:a9e4b9eb6c59f62389495a',
    messagingSenderId: '283652485039',
    projectId: 'new-online-shop-74b83',
    authDomain: 'new-online-shop-74b83.firebaseapp.com',
    storageBucket: 'new-online-shop-74b83.appspot.com',
    measurementId: 'G-Y3HKP14VBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvyV7sHjkHat5-2ZH8OqxZ8RRPBt9n-D4',
    appId: '1:283652485039:android:25243133e0abe26789495a',
    messagingSenderId: '283652485039',
    projectId: 'new-online-shop-74b83',
    storageBucket: 'new-online-shop-74b83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFn_V7Z7dMDThcrT5D9ceXntzWnFGiqE0',
    appId: '1:283652485039:ios:4b870fcb031dffdc89495a',
    messagingSenderId: '283652485039',
    projectId: 'new-online-shop-74b83',
    storageBucket: 'new-online-shop-74b83.appspot.com',
    iosBundleId: 'com.example.flutterApplication',
  );
}
